backend:
  name: test-repo
  repo: vieiramanoel/blog-gatsby
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: blog
    label: Blog
    folder: src/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }